### ISSUE TITLE
关于指挥官可以让僵尸阵营看到

### ISSUE THREAD

**Issue by dongdaoyu** [CSGOGAMERS-Community/CG-Server#108]
我建议指挥官不要让僵尸阵营看到，因为有些地图比较复杂，需要指挥官去带萌新走，所以这条路上的断后能力会很差，但是僵尸能看到指挥官就知道先抓这里，因为断后能力差，对很多萌新不是很友好，建议指挥官不要让僵尸阵营看到

**Comment by Kxnrl** [comment]
DONE
