### ISSUE TITLE
Feature: Mutators

### ISSUE THREAD

**Issue by LorlieAsh** [CSGOGAMERS-Community/CG-Server#11]
*已附中文，看不懂请自学CET4
 - Inspired by feature with same name from "Co-op missions" mode from Starcraft II: Legacy of the Void.
 - Mutators are special conditions that bring additional challenge and diversity to designated existing maps in server.
 - Mutators can vary wildly, from limited ammunation for weapons, to control movement speed to avoid trigger_hurt :D.
 - Mutators vary on a weekly basis. Each week, players have the chance to take on a Weekly Mutation where several Mutators are applied to designated map/mode.
 - No limit for players to test the mutators.
 - If players complete the weekly mutation, they will be awarded a tiered Credits/Rank "bounty" bonus based on the difficulty map selected.

The following mutations are available for conception:
Barrier: Enemy units gain a temporary shield upon the first time they take damage.
Vertigo: Your camera randomly changes positions.
Flammable: Some enemy carry some flammable liquid that deals damage over time and spreads to other nearby units. The flame spreads to you when the nearby enemy is killed.

To be continued, think in progress

Drawback: consume lot of computing of server seriously, maybe.

好吧，上面只是稍微official一点的写法，中文我就随便写了
这个想法是构思在星际2合作任务的突变模式上面
**不过只是个设想，实际我觉的可行性不大，因为实现这种效果会消耗大量的服务器资源，就当看个乐呵**

以下是根据星际2国服官网改来的介绍文字
突变因子:
　　突变因子是为增加现有地图的复杂性与多样性而推出的特殊游戏机制。突变因子的变化幅度非常大，有时候你需要对抗完全隐形的敌方阵营，有时候又需要躲避突如其来的坠落陨石，有时候你需要保持85单位的移动速度来避免被trigger_hurt弄死。
　　突变因子每周更新一次，每周在指定的地图上玩家都可以体验到不同的突变因子。
       每天的特定时刻，玩家都可以通过发起投票来发起是否开启突变因子的投票，当同意开启人数达到一定比例(90%或者更高)时将开启突变模式。每次突变模式投票间隔不得低于24小时，每次突变模式开启的时间不超过30分钟/当前地图终场，以免影响普通游戏。
       判定胜利条件:在突变因子开启后得分最高者(MG等服务器可能设为FRAG最高者,ZE可能为伤害最高者/通关最多者等，视情况而定)
         如果玩家能征服一次“每周突变”，其会获得大量的RANK奖励分数以及一定的Credits，每周只能获得一次。
         _突变因子大多数是用来整人的，玻璃心请勿轻易游玩该模式。_

**Comment by CGMentos** [comment]
现在猫灵落下几十万份各种功能没做，还加个dick Feature。你可拉
而且这种，又要萌新学习，本身talent啊，钻石、热度，各种各样名词够多的，还来这个，而且不动就trigger_hurt。

**Comment by Kxnrl** [comment]
然后我没看懂

**Comment by LorlieAsh** [comment]
呃
就是说，在正常游戏的基础上设置一些限制，比如[限制玩家以85移动速度/蹲姿移动否则将受到伤害]或者说[某一阵营模型在限定时间内全体模型alpha100]这样的一些变动，增加一些不确定性和随机性，就跟当初MG丢O3那样raffle到范围数字就死一样...
而且这个思路可以一次性套用到大部分类型的玩法里面
另外@CGMentos 这个Feature能做的成的话都是要vote开启，vote写清楚萌新慎选，他选了自己被虐死就不要bibibibibi了
trigget_hurt不一定要用到啊,选择一些不影响服务器正常运作的方法就行，这里只是举个例子。
(### 说的好像踢踢踢的某些想法都很正常 :| 不过这就是我自己开了一下脑洞而已，具体能不能行取决于技术可行性)

**Comment by Kxnrl** [comment]
说白了就是跟我以前忍者服
一定概率发生突变差不多(当时是 黑夜|中毒 突变)

**Comment by LorlieAsh** [comment]
但是这个就多样化一点
还可以照抄玻璃渣做过的因子罢了
采不采纳由你

**Comment by Kxnrl** [comment]
把ZE的策划写详细点

**Comment by DohiCircle** [comment]
弱弱加一句有点隔壁183ZE模式的感觉
不过……

**Comment by CrysisDeathgun** [comment]
蛤。。然而JailBreak一万个bug还没修

**Comment by Kxnrl** [comment]
哦,JB一个ISSUE没见到,修什么,我不知道有什么BUG反正?

**Comment by Kxnrl** [comment]
已更新至MG服务器
- 一冲到底
- 横着走
- 神经毒素
- 强制TP

还有其他的还在测试

**Comment by LorlieAsh** [comment]
@DohiCircle 我没记错的话183ZE那个要吃蛋触发而且只针对吃到的玩家吧?
这个是全局效果

**Comment by Kxnrl** [comment]
done
