### ISSUE TITLE
ZE相关建议

### ISSUE THREAD

**Issue by hjhavoc** [CSGOGAMERS-Community/CG-Server#117]
僵尸逃跑需要整改的地方:
第一:人数问题 我觉得可以取消掉自动屏蔽人物模型  （因为有些会开麦说话的人第一句就说:我怎么看不到队友？其次是说，该怎么玩，正是因为这种情况有些人会玩不懂，选择退出服务器）
看见队友了，有人开麦 撤退 就会跟着大部队走，而不是迷路
第二:地图bug问题，cg僵尸逃跑是一个非常年轻的服务器，神图的一些bug，必须得修，只有神图才能吸引一些老玩家，（如果一张神图没有老玩家，只靠一个指挥官带图的话，这张图需要每一天玩，需要一个多星期时间才能正常玩，而且，服务器内的常驻玩家还的禁得起每天玩一张图的痛苦，比如蘑菇2，而且指挥官还的讲解每个点的守法等等，非常累 ）
有老玩家的情况下，就会老玩家拿神器 ，会帮忙断后，大大提高服务器内的战斗力。
（一些有志气的萌新他们自然而然的就会观察到那些老玩家是怎么玩神器的，那么萌新就会敢去拿神器，长经验，服务器常驻玩家战斗力就会提高）
第三:取消掉拿神器需要的分数，这个问题很关键，（不要怕什么萌新拿神器乱开，会玩的人自然就会去抢神器，在我看来萌新乱开神器的例子非常少发生，即便乱开 老司机也会慢慢的教导他该怎么玩神器，ze高玩也是这样需要上一代人的培养，这样战斗力也会提高）

上面三点基本上都提到了，如何提高人数，吸引老玩家，提高常驻玩家战斗力，等等
做好了，服务器绝对有人

现在服务器内的小问题 母体僵尸击退
神图bug:游乐园尸变数量，地图手雷（改了绝对吸引一些ub的老玩家）
minas分数，以及僵尸神器拿不了问题
上古卷轴 大卫用不了 
里拉大冒险，地图手雷，神器分数问题
地图手雷是地图参数，很容易改
接下来是  minas，里拉大冒险，神器等级分数问题 以及僵尸神器拿不了

个人的一些建议:可以多增加一些僵尸模型种类
枪支击退改高（我发现服务器里的人不喜欢扔高爆 火瓶，那么就不如提高枪的击退，）
取消火瓶，增强高爆减速时间以及影响范围，高爆数量，价钱进行调整
冰冻手雷留着
聚合雷改成一次爆发性伤害，伤害稍微提高些（现服务器内聚合解冰解火效果）
屏障雷留着
指挥官插件的修改建议:站在指挥官傍边打僵尸打到一定伤害时送你一颗手雷

现在ZE的处境比较危险，希望能改一次试试。
如果一次不行就继续想办法，一直到解决为止

**Comment by Kxnrl** [comment]
游乐园垃圾图因为炸服已经删了
