### ISSUE TITLE
一些服务器意见

### ISSUE THREAD

**Issue by hjhavoc** [CSGOGAMERS-Community/CG-Server#119]
1.消除人少自动跑图，改为OP设置 
2.删除未注册插件，并且在左下角加入滚动提示：!hide可以显示/隐藏队友。  ，可以打开商店   F3购买武器手雷
3.对提供地图，翻译，协助修改CFG的玩家提供积分奖励
4.设置地图组认证，重新开放测试组等官方组织，提供热度加成与奖励
5.根据热度值赠送免费期限皮肤，热度值增加在线积分，考虑从商店中选取热度专属模型
6.削弱母体
7.开放新玩家赠送大头（最好是时间卡到足够一定热度，然后发放期限热度奖励，给新玩家玩下去的动力）
8.所有OP下权，重新申请
9.恢复地图手雷，修复地图分数BUG
10.通过神图送期限皮肤
11.削弱人类子弹
12.对伤害前5进行积分奖励，删除聚合，屏障价格上涨为1W5

根据优先度进行排列

**Comment by CGMentos** [comment]
第八条,说说为什么

**Comment by CGMentos** [comment]
屏障涨价是否有足够信心让玩家更容易通关,为什么

**Comment by hjhavoc** [comment]
第八条，因为存在部分OP长期AFK的状况，所以建议全部下权，给其他玩家申请OP的机会，同时也让现有OP重新申请，来证明当OP的决心，仅为个人意见

**Comment by hjhavoc** [comment]
屏障降价是在母体削弱的前提下，可能僵尸会有所削弱，所以提出这个建议来平衡。也希望适当的减少子弹。

**Comment by Kxnrl** [comment]
ZE现在的插件已经很落后了.不更新不行
但是我根本不更新什么.OP也不会提什么实际性的已经
甚至连加地图,都不会.

**Comment by hjhavoc** [comment]
加图的事情，我已经把教学帖子传播了，昨天已经有玩家上传新图，至于插件落后，希望能一步一步来

**Comment by Kxnrl** [comment]
你确定他们的地图都经过测试吗.

**Comment by hjhavoc** [comment]
单机应该没问题，放入服务器中不知道如何

**Comment by Kxnrl** [comment]
你确定单机测过了/?

**Comment by hjhavoc** [comment]
从GFL那边拿的图。感觉这种事光靠OP是不行的，如果能出现电脑自动更新，或者玩家能加入。效率会提升很大。

**Comment by Kxnrl** [comment]
你语文学好了吗

**Comment by hjhavoc** [comment]
没有。不确定单机是否跑过，其中有我的疏忽
