### ISSUE TITLE
服务器意见

### ISSUE THREAD

**Issue by hjhavoc** [CSGOGAMERS-Community/CG-Server#128]
社区意见
一丶调动玩家自觉性
1.设置地图组认证，重新开放测试组等官方组织，对官方组织成员发放奖励（OP，各官方组织成员），奖励最好为稀有奖励，以带动积极性
2.对提供地图，翻译，协助修改CFG的玩家提供积分或模型奖励
3.清除AFK  OP，OP若长时间不在需要说明
二丶调动新玩家积极性
1.开放新玩家赠送大头（最好是时间卡到足够一定热度，然后发放期限热度奖励，给新玩家玩下去的动力）
2.根据热度值赠送免费期限皮肤，热度值增加在线积分，考虑从商店中选取热度专属模型

ZE服务器意见
一丶服务器风气调整
1.制定服务器规则，明确OP权利
2.倡玩家进行CFG修改，地图添加，测试，BUG反馈等活动，并提供相应奖励
4.恢复小学生认证，暑假人多，肯定需要大量整治，小学生比直接BAN来的更好
二丶地图相关
1.修复地图手雷问题
2.修复当前已知BUG（西沙人类皮肤，游乐园多个僵尸尸变，地图分问题等）
PS：由于培育一个玩家的成本远远大于吸引一个厉害玩家的要大，良好的服务器体验是吸引他们常驻的基础，假如开设2F，社区实力不够,2F计划将会破产，故此条非常重要
三丶服务器本身调整
1.	削弱人类子弹
2.	给予OP CFG修改的直接权限，或改为OP相互审核
3.	对伤害前5进行积分奖励，删除聚合
4.	在左下角加入滚动提示：!hide可以显示/隐藏队友。 ，可以打开商店 F3购买武器手雷之类，并且给予OP修改的权利
5.	通关神图赠送皮肤，整点ROLL皮肤
6.	下调部分地图定图积分
7.	提供暖服奖励，例如积分加成，人工对服务器在线时间长人员发放奖励
8.     完善!hide屏蔽插件，玩家输入!hide后，可以选择，屏蔽范围，是否屏蔽认证玩家，是否屏蔽。更为人性化
PS：暖服插件构思，15人以下给予额外积分，当一个玩家额外积分到达一定时，系统送出期限皮肤作为奖励

吸引大佬，照顾萌新，应该优先朝这两个方向发展。
可能ZE需要的东西太多了，但是，希望能得到理解，ZE也是最容易发展起来的模式之一，能为社区带来大量人气

**Comment by Kxnrl** [comment]
PS：暖服插件构思，15人以下给予额外积分，当一个玩家额外积分到达一定时，系统送出期限皮肤作为奖励 刷分新途径

给予OP CFG修改的直接权限，或改为OP相互审核 拉鸡巴倒吧.就那智商

**Comment by hjhavoc** [comment]
我指的是信用点，多挂一点机，拿一些信用点，应该也没啥不妥把。。
CFG没关系，其他的能通过就行

**Comment by Kxnrl** [comment]
就是挂机拿钱,以前就有,你这样运营迟早倒闭
