### ISSUE TITLE
越狱BUG

### ISSUE THREAD

**Issue by DohiCircle** [CSGOGAMERS-Community/CG-Server#131]
如果选择赛跑 CT自杀 T会悬空冰冻 然后就动不了 !stuck无效

**Comment by Kxnrl** [comment]
卡LR了

**Comment by DohiCircle** [comment]
我使用彩虹字体第一个答数学题 对的但是不算我答对 好像复制是变成 51[ret] 很气

**Comment by Kxnrl** [comment]
那你试试不用彩虹字体,还会这样吗

**Comment by CrysisDeathgun** [comment]
囚犯捡了神器之后第二局在空中被打死 第二局囚犯还具有神器的效果（单一效果）只有重力效果 血量和速度正常

**Comment by Kxnrl** [comment]
重力BUG是因为垃圾地图导致的.

**Comment by Kxnrl** [comment]
fixed
