### ISSUE TITLE
ze一些功能建議

### ISSUE THREAD

**Issue by EriKa-Laser** [CSGOGAMERS-Community/CG-Server#137]
## 天赋
我希望ze能个别重做一次天赋，因为有部分天赋影响了ze的平衡性。

1. 伤害：我建议削弱2成。
2. 速度：我们不是丢东西就切刀跑，而是边断边退，建议削一些。
3. 暴击：跟伤害一样。
4. 护甲：这东西只是减枪支的伤害而已吧，而且只加3护甲，就算殭尸有这护甲也只能挡１次子弹吧，有什么用。不然可以改成「减伤」降低部分摔落伤害吧。有VIP减摔的1成就已经很好了。
5. 吸血：可以保持。
6. 生命：可以保持。要是护甲能改成降低摔落伤害就能和这个发生加成反应。生命＋减伤的效果。
7. 子弹：这个我希望可以在天赋中取消，改成是每使用多少发子弹，就送部分备弹，比如说我用ｍ４ａ１打了５０发，就送２５发备弹。能有效解决打正常图时萌新容易缺子弹的问题。而且我们老玩家多数都会直接重新买一把枪支，这个子赋就显得没什么意义了，加上打ＢＯＳＳ有钱送。
8. 进化：这个天赋我希望可以分成２个阶段，第一个阶段就是固定跳跃，把游戏时的跳跃能力固定提高２～３lv吧，这样就可以使萌新比较容易成功跳点，比如说屋檐一开始的跳箱子在没天赋也挺难的，这样改就能变得不太难也不容易。而且加２～３lv也不会影响到跳刀的问题。而第二个阶段就是现在的进化天赋，我希望能够大幅度削弱甚至取消（前置条件要提升固定跳跃高度），因为这一个天赋影响了平衡性，逃跑的地图作者正常都会为玩家想好怎么守一个点，但是我们ＣＧ服的跳跃太高导致可以让殭尸直接跳点，这直接让人类失去了一个拥有作者用心制作的守点，比如说疯狂逃脱，第２关的最后是有一个木桥的守点，殭尸是只能中间的木桥进攻，而我们ＣＧ服的殭尸就能在旁边直接跳，人类从一个单独的守点变成全范围的防御，那不就变成殭尸单方面的胜利么。
9. 闪避：据说欧洲人可以点这个防人类子弹破点，这个就保持吧。

# 断后奖励
为了提高断后的积极性。
我们ＣＧ服是以手雷为主要的防止手段，就应该对手雷那方面和断后切合在一起。
因为断后为逃跑的主要手段之一，以天赋那方面的子弹来说，转过来为断后奖励运用，射击多少发子弹就送部分备弹，这样就能更有效运用子弹。
另一个就是对殭尸输出到一定伤害，就送一颗手雷作为奖励。这样就能让断后有更好的保障。可以在前线积极断后，要退的时候就可以丢手雷退。
这样也可以让社区以手雷多著名的特色发挥起来。

# 游戏开始时的尸变
我希望可以从现有的挂机尸变改成，上局输出伤害愈低尸变机率愈高。当然，输出高的也是有可能，只是机率低而已。提高断后积极性的同时，也可以防止一个人连续做殭尸。
以上面的方案，是要防止第一局变殭尸的玩家被判定0输出的，希望可以弄一个排除掉殭尸阵营的输出。输出判定开始算的时候是尸变后才开始算。

# 游戏中的提示
每次都是要OＰ输入才有的提示，那到底有什么用。而且左下角的滚动提示，没人说我都根本不知道有这东西
萌新通常都不会注意到左下角会有提示这东西，若是能放在一些很容易注意的位置就比较好了，比如说在准心的下面一点，在这里放些提示也可以。而且提示希望是全自动的，而不是OＰ输入才有的——(注:可以设置一个屏蔽掉的指令，这主要是针对萌新的)
提示就比如说：(每15秒就随机抽一个出来提醒，几秒后消失，一个循环)

- 按键盘上的shift／F3键就可以选择购买枪支和手雷
- 要是不幸卡在地形上，可以在聊天栏上输入!ztele脱离(注: !必须为英文字体)
- 神器是按e键使用，所以请勿按e抢神器，要是你拿了神器，你就要有相应的觉悟去断后和合理使用(包括萌新)，乱用神器和拿了不使用则会受到严重的处罚
- 要是感觉到卡或者看不到路，可以输入!hide屏蔽身边的人，要是看不到队友，可以输入!hide把屏蔽设置为0(注: !必须为英文字体)
- 在有人指挥的情况下，严禁抢麦和闲话，违者禁言
- 打BOSS时请勿打殭尸，这样你会是队伍中的毒瘤
- 游戏时请把声音打开，因为地图可能会有陷阱，有人提醒时，你没去听而死就会成为队伍的累赘
- 请萌新积极断后，不然下局会有很大机率尸变。

# 神器的显示问题
我希望是改成有人拿到神器才显示，人类是以现有的神器来作策略的，而不是知道多少神器就可以的。可以训练指挥官的神器运用。
而殭尸和人类的神器，希望能够分开显示，比如说我是人类，我能看见人类神器持有者和CD，但看不见殭尸神器的持有者和CD。这样能够让对面互相猜测和收集情报(殭尸可以从人类的指挥中听取和看人类使用的神器得知有什么神器，人类可以通过断后观察殭尸有没有神器和判断神器的CD)。
这样可以让人类增加刺激性，因为你不知道殭尸的神器持有者会甚么时候进攻。殭尸神器持有者也可以来一个出其不意。如何防守就成为人类的一个合作难点。
而显示的位置可以放在准心的右下方的位置之间
排列顺序是 神器名字[CD]:持有者
这样可以把地图重新显示出来，地图是很重要的!!又能看到神器的使用者和CD。

# 左下角聊天栏
虽然有个屏蔽全服聊天指令，但还要拿出来说一下
我希望能够把全服聊天默认屏蔽，那是老司机才会这样说话的吧，萌新根本就不需要看这些。只需要去看在这个服务器说的话就好了。
老司机想去对话就打那个指令就好了啊。

------------------------------------------------分割线----------------------------------------------------

可以尝试一下把修改cfg的权限分给OP，如果你觉得不行，OP列表不是有个权重等级么，让那些对ze贡献特别大的OP提升0.1权重，也就是cfg修改权。然后观察一下啊，一来又能分担压力，又能增加人手，再来又能使效率增高。

**Comment by Kxnrl** [comment]
**天赋**
伤害: 精通也只有12.5%,也就是你一枪30最多能打34,多4点.
速度: 精通也只有12.5%,这个可以考虑再ZE削弱一些(僵尸没有速度天赋)
暴击: 概率太低,精通只有6.25%,100枪才6下,我觉得没必要削
护甲: 减弱收到的由玩家造成的伤害,减弱坠落伤害(VIP -50%)
子弹: 不考虑你的建议
进化: 僵尸没有进化天赋.只有人类才会生效进化天赋

**断后**
送手雷就免了吧,我现在玩的少,也不清楚用什么算法计算断后最合适,反正肯定不可能只看伤害.
射击送子弹,太扯

**尸变**
尸变是完全随机,每个人概率一样.你要用那种随机,会稍微一些复杂.起码目前短时间没办法实现.
现在尸变逻辑是 挂机>不和谐组标>开局自杀>上把贴门>正常玩家.

**提示**
overlay已经做好但是没有更新.
左下角和中间的滚动提示,一直都有,只是没有人去维护.

**神器**
HUD分开显示阵营是可以的,但是你计分板怎么显示呢.
右下角显示HUD会显示不全.(如果地图神器比较多.)
关闭!ehud就可以显示雷达(或者你直接TAB也能看到雷达)

**聊天**
呵呵

**CFG**
个别OP一直有直接写入权限,他们学不会怎么用而已.这个问题我不负责

**Comment by EriKa-Laser** [comment]
既然殭尸不会对天赋生效，那么
护甲：不会有人类能打到人类扣血的吧...
进化：那人类的进化能否分2阶段呢，就像以上说的那2种，让萌新更容易跳起来而又不影响老司机跳刀。想跳更高也可以点进化。
子弹：现阶段子弹天赋绝对是一个强力的天赋，可是在当前ze各种情况下，我没有理由需要点这个天赋。比如说补给，组标，打BOSS送钱，根本就不乏买新枪的钱。
与其浪费掉一个强力天赋，不如让它能够成为一个能在战场紧急时候能发挥的天赋。
这就是我的想法

神器
计分板那个倒是不知道怎么取消显示，如果解决不了，希望能尝试把双方的CD互相隐藏掉，我作为人类能提前知道殭尸神器的CD也太扯了。

殭尸能力
天赋不影响殭尸能力
希望能把殭尸的跳跃能力降低一些，相对速度就提升一些。
老是跳去一些本不应该能跳过去的地方破点==

**Comment by Kxnrl** [comment]
HUD已经调整

**Comment by EriKa-Laser** [comment]
用现在弄好的HUD再分阵营看就完美多了，就算用tab知道有也不知道CD a-a

**Comment by EriKa-Laser** [comment]
按錯了... 用现在弄好的HUD再分阵营看就完美多了，就算用tab知道有也不知道CD a-a
