### ISSUE TITLE
关于JB建议

### ISSUE THREAD

**Issue by CrysisDeathgun** [CSGOGAMERS-Community/CG-Server#139]
每当CT队伍里没有一个会玩的狱长或者狱长玩的不成熟 那么排队成为狱警的就近似没有 而随机到成为狱警的玩家会选择跳观察再跳T 或者直接跳T 这样刷来刷去就很傻逼 

那么改进建议是 加规则或加一个检测条件 刚刚随机到的狱警必须玩一个回合 如果跳了T或跳了观察自动处死并加一个锅

**Comment by CrysisDeathgun** [comment]
再来个 囚犯恶意坑队友 坑一个背一个锅
举例 小明在没有狱长命令的情况下 去开车 而坑死了囚犯 土肥圆 鲁迅 曼妥思 他需要背3个锅

**Comment by Kxnrl** [comment]
现在不允许直接跳T
