### ISSUE TITLE
越狱平衡狱警插件问题

### ISSUE THREAD

**Issue by PERFECT44** [CSGOGAMERS-Community/CG-Server#141]
现CTBAN命令中 有随机部分狱警不显示在CTBAN菜单中，导致违规不能BAN，另被ban的玩家依然可以无视CTBAN被插件拖至狱警队列。
请求删除LR游戏中的赛跑游戏，看不到终点CT基本没有机会赢，导致囚犯狱警不平衡。

**Comment by Kxnrl** [comment]
CTBAN将会取消
