### ISSUE TITLE
服务器禁言无法解除

### ISSUE THREAD

**Issue by zhenxiaoxiao** [CSGOGAMERS-Community/CG-Server#142]
禁言之后无法解除，显示 ：数据拉入失败

**Comment by Kxnrl** [comment]
截图有不

**Comment by zhenxiaoxiao** [comment]
![20170801181140_1](https://user-images.githubusercontent.com/25277820/28820701-2f787bd8-76e5-11e7-9595-21b5ef69cbf2.jpg)

**Comment by Kxnrl** [comment]
已更新,等待推送到服务器
