### ISSUE TITLE
TTT建议

### ISSUE THREAD

**Issue by zhenxiaoxiao** [CSGOGAMERS-Community/CG-Server#143]
0.多加一些ttt地图
1.加强触碰炸弹（使其能在门上生效）
2.加强遥控炸弹（4步范围内造成200伤害，4步以外伤害递减）
3.重甲改为350加普通护甲（头甲必须要）
4.加高枪支的出现率
5.op刷枪指令枪械分类再详细化，（狙击枪不加入步枪系列，不参与步枪随机，机枪不加入霰弹随机
op能够选择该地图刷枪是否随机，op能够删除地图枪械）
6.ttt服务器加入CG官方组点数加成（吸引玩家）
7.重启人品值过低无法随机到叛徒和侦探机制。同时弹出左侧规则提示（该提示无法关闭，只能按7翻页一直到规则结束才可退出）
8.服务器自动2分钟就在聊天框提示 输入！rules查看规则，不可猜测杀（该提示以红色字体3连发模式发出同时发出哔的一声）
9.服务器2分钟自动提示论坛网址，注册论坛
10.萌新福利再度来袭，注册就送大头皮肤3天加xxxx信用点
11.老玩家回归送14天随机皮肤加8888信用点（回归玩家为30天内未登录服务器的玩家）
12.开启充值送送活动！（累计充值100送7天皮肤！200送30天     单次充值100送7天皮肤加永久聊天字体！200送30天皮肤加永久足迹）

**Comment by Kxnrl** [comment]
0. done
1. 伤害不变,范围加倍
2. 伤害不变,范围+100u
3. 直接增加重甲的移动速度
4. done
5. done
6. TTT没办法挂组标
7. 人品不够150不能当T,不够300不能当D
8. ???
9. ???
10. ???
11. ???
12. ???
