### ISSUE TITLE
ZE—指挥官增强、奖励增加计划

### ISSUE THREAD

**Issue by CGMentos** [CSGOGAMERS-Community/CG-Server#15]
新增一个功能让OP能ban掉没有麦克风的玩家，使其不能当指挥官。

增强功能：

1. 指挥官在所有地图初始金钱数+10000
2. 指挥官在神图补给点补给所有手榴弹数+1
3. 指挥官所有可购买手榴弹+1
4. 指挥官在神图以人类通关获得概率获取钻石奖励，并且100%获得的信用值奖励，奖励值为通关CT数乘以88点信用点
5. 新增让指挥官、OP能强制显示所有玩家头上名字（方便能让指挥官、OP看到谁在神图打BOSS的时候刷僵尸，点名批评甚至处死）

**Comment by Kxnrl** [comment]
第五点就是神经病,前四点手雷不可行,其他的一直都有
还有,手榴弹是什么J8,玩CF?

**Comment by CGMentos** [comment]
有请古代人@Kxnrl 补充一下现代中文知识
https://zh.wikipedia.org/wiki/%E6%89%8B%E6%A6%B4%E5%BC%B9

按我此法增强指挥官，大佬抢着当指挥官。不这样增强无所谓，一个建议而已，反正很多图没人乐意当指挥官，与其下了这插件，不要这心血，不如大加强，反正只有一个指挥官。
