### ISSUE TITLE
TTT bug及建议

### ISSUE THREAD

**Issue by zhenxiaoxiao** [CSGOGAMERS-Community/CG-Server#152]
1.上一把是叛徒，在这把出身份之前能够打开叛徒房
2.100发A1购买之后没有主弹夹，换单后变20发

建议
1：在现在人品低的时候弹玩法的基础上加上 在线不足20小时的玩家每局都弹玩法和规则
2。平民被大D错杀不能处死大D，但是如果错杀3个人就处死大D

**Comment by Kxnrl** [comment]
1. fixed
2. HoldON

**Comment by Kxnrl** [comment]
DONE
