### ISSUE TITLE
TTT 莫名其妙崩溃

### ISSUE THREAD

**Issue by YangChongQuan** [CSGOGAMERS-Community/CG-Server#157]
2017-08-19 16:11:  上一次大概是  16.00 十分钟左右连续炸两次(就是游戏突然没了   全部人都是)  地图名ttt_minecraftcity_slayers_v1_fix1 
服务器： 1服。
补充 ： **# 秒杀刀BUG  买了没有。 点也扣了。**

**Comment by YangChongQuan** [comment]
秒杀刀最新情报。  原版刀买了 会出现黄金刀 有秒杀效果
不是原版的 买了扣点  刀不变 没有秒杀效果

**Comment by Kxnrl** [comment]
原版刀买了会出现黄金刀是什么意思

**Comment by YangChongQuan** [comment]
就是 没装刀 皮肤的  才能买到黄金刀 。
比如我装了把刺刀买黄金刀 扣点了 我的刀还是刺刀没有秒杀效果。

**Comment by Kxnrl** [comment]
那你装了商店里面的皮肤刀,什么效果

**Comment by Kxnrl** [comment]
fixed
