### ISSUE TITLE
JB bug 8/24

### ISSUE THREAD

**Issue by TendoukyuYiyi** [CSGOGAMERS-Community/CG-Server#159]
1.最后一个狱警以及工程插件时候，丢烟雾弹和闪光弹不会处死加锅。
2.刷枪处死插件飞了！不见了！
3.AWP好像也会被判定连狙，处死加锅。
4.连狙加锅变成两个了。
5.狱长触发最后一个狱警插件只有100血。
———————————————————————————————————————————————
意见=-=
1.下攻城插件需要200信用点
2.vip可以当局花1000信用点不被强制换队
3.越狱商店可以用信用点买：1商店积分=100信用点。
——————————————————————————————————————————
宝宝不喜欢写issue。宝宝很难受

**Comment by Kxnrl** [comment]
bug:
1. fixed.
2. fixed.
3. non.
4. OnHold.
5. fixed.

suggestion:
1. FR.
2. FR.
3. FR.

**Comment by Kxnrl** [comment]
suggestion:
1. done.
2. done -> 2000credits.
3. done -> 1$:50credits.
