### ISSUE TITLE
关于今天的出现的一些问题

### ISSUE THREAD

**Issue by EriKa-Laser** [CSGOGAMERS-Community/CG-Server#162]
早上的时候就出现了购买手雷等物件无限的情况。
只要一开始购买了屏障，就可​​以一直无限丢屏障。如此类推。

旧事: 自从v社那次大更新后，子弹类神器全部失效。
         使用時并不会有无限子弹的效果。

米纳斯p4的地图专属模型希望能去掉，因为这是唯一不会炸的版本了。

#ze bug

**Comment by Kxnrl** [comment]
fixed
