### ISSUE TITLE
越狱BUG （8.30）

### ISSUE THREAD

**Issue by 827441119** [CSGOGAMERS-Community/CG-Server#163]
1.狱警无法获得加血针。

2.当最后一个狱警是狱长还是只有100左右HP.

3.获得武器，弹夹中没有子弹，都需要换一次弹夹后才有子弹。

4.下狱长后有些狱警“距离狱长过远”HUD一直显示不会消失。

**Comment by 827441119** [comment]
4.下狱长后有些狱警“距离狱长过远”HUD一直显示不会消失。

**Comment by Kxnrl** [comment]
fixed
