### ISSUE TITLE
ZE收集来的一些反馈

### ISSUE THREAD

**Issue by LorlieAsh** [CSGOGAMERS-Community/CG-Server#18]
*风气问题↓
*麦霸太多以及卡麦现象严重/HLDJ滥用
*所有带投票的feature拉票现象严重，尤其是分数高的玩家换图以及commander
*瞎指挥，有质疑就粗口骂人
*新的molotov范围太远? 有反映影响范围超过250U，甚至跨墙/跨楼层烧
*无限延长

有关ZE认证、VIP以及管理↓
*自动认证:ZE认证入门门槛是否太低?刷分现象过多导致高分低能玩家暴增(几千分连地图机制都不知道?还跟真正有经验的玩家顶嘴?)
*VIP滥权有些严重
*↑这一部分人看到有OP在时很安分，没OP在就跳 /是否关闭ZE admin显示?
(OP除非小号，否则是抓不到捣乱者的)

*!pb支持覆盖范围@all
***尽快制定新的服务器规则!!!**
*是否增加进服强制查看规则?
*清理一下认证玩家?
*Disable按钮发光? /把真正有经验的玩家和智障区分开来?
*缺少有话语权的玩家，而不是能哗众取宠的人
*用TTT的手段来整治ZE

**Comment by CGMentos** [comment]
风气问题：

> 解决不了，人多傻屄自然多

麦霸问题：

> 正常，玩家喜欢聊天，在有指挥官的时候ＯＰ可以ＭＵＴＥ，ＯＰ不管那更没办法管，难道不够多少积分不给别人开麦吗，不可能的，如果真的实现不够积分不给开麦会引发连锁反应。

拉票问题：

> 猫灵已经出过方案。说是谁预订神图，在换了之后左下角每分钟提示一次谁换的。顺便强制他是指挥官。
个人认为最好加个指令让ＯＰ设置某玩家以后预订任何地图所需信用点＋５０００

瞎指挥：

> 有其他社区玩家（点名Ｘ社区）开始“转区”，正常。

无限延长：

> 好玩就延长，没毛病．按５按６都是玩家票选的．不要只有一个人反对无效来申诉你就记下来

# 我发现的问题
－理应调整更多认证，认证门槛提高．
－增加扣分机制，比如买聚合雷额外要花费３积分；比如在神图每被感染扣１分（比检测ＡＦＫ好用）等等……
－手榴弹上限理应调整更多，有些玩家反馈发现买手榴弹９粒是上限但是没有任何提醒原来有上限，打ＢＯＳＳ的时候花了钱没存到雷，“ammo_grenade_limit_default”、“ammo_grenade_limit_total”调整到更多

**Comment by Kxnrl** [comment]
手雷上限,再加,Entity就超2048了,10个是极限了,而且是建立在删掉很多东西的基础上.
聚合雷额外扣钱会考虑
认证门槛已经挺高了
