### ISSUE TITLE
ZE服燃烧瓶升级改造

### ISSUE THREAD

**Issue by CGMentos** [CSGOGAMERS-Community/CG-Server#19]
改成丢出去一定范围爆炸,最好参考高爆的距离.
给爆炸范围内僵尸加个持续X秒的燃烧效果,减速效果
+燃烧伤害.伤害有钱奖励
+减速效果.减速渐渐恢复正常,而不是一直减速多少多少然后立即恢复正常.

**Comment by Kxnrl** [comment]
Ignite=炸服炸SV
