### ISSUE TITLE
JB服——投票踢出狱长改进／加入积分制

### ISSUE THREAD

**Issue by CGMentos** [CSGOGAMERS-Community/CG-Server#22]
# 1.未注册不能投票踢出狱长
# 2.越狱积分永驻制，也就是跟现在逃跑服一样，而且分等级。
### （Ｔ） 囚犯
囚犯每回合首个击杀————————————**＋３积分**
囚犯每回合首个对狱警造成伤害的——————**＋２积分**
> 第一个击杀狱警的不一定是第一个暴动的，但是第一个暴动的一定是第一个对狱警造成伤害的．

囚犯获胜（存活人数大于２人时）——————**＋１积分**
> 防止专门喜欢蹲时间到ＬＲ的怂逼为了积分卖队友

囚犯当局累积承受大于９９点伤害——————**＋１积分**
> 给予那些玩囚犯有技巧，耐肏的玩家适当的奖励

### （ＣＴ） 狱警／狱长
ＣＴ第一个击杀第一个对狱警造成伤害的囚犯—**＋５积分**
ＣＴ获胜—————————————————**＋１积分**

**Comment by Kxnrl** [comment]
统计系统都没有,怎么引入积分制= =
