### ISSUE TITLE
全服VIP权限升级——投票功能CD降低

### ISSUE THREAD

**Issue by CGMentos** [CSGOGAMERS-Community/CG-Server#23]
年费、永久VIP【投票踢人】、【投票ban出】、【投票禁言】、【投票封麦】功能由每个用户最快30分钟投票一次降低至每个用户最快5分钟投票1次。

如果可以，把功能做成要按Y发送!yes和!no用作投票选项，超70%用户投票yes为通过。

**Comment by Kxnrl** [comment]
5分钟一次,6哦..朋友......
而且tm玩到一半,还要按Y投票,你不觉得很弱智吗...
