### ISSUE TITLE
TTT电击不死颜色保留到下一局

### ISSUE THREAD

**Issue by YangChongQuan** [CSGOGAMERS-Community/CG-Server#24]
① 比如第一局我是“平民” 被电击 绿色，这局我没死。第二局开始我就是“绿色”，然后出身份我是“T”，这把我杀光所有平民没死，第三局 开始我还是“绿色的”。
② !seeme 失效
③ TTT点数会保存到下一张地图
④ 大D死亡说话能看到。  dead 我是大D：啊啊我被打死了 他是T啊。
⑤ 认证没有点数加成。

**Comment by Kxnrl** [comment]
①已修复
②!seeme对于绑定快捷键的玩家来说仍会破坏游戏平衡/加上现在!store允许预览,决定在非娱乐模式取消
③现在不再保存,只保存当前地图,玩家掉线时恢复点数
④需要进一步测试
⑤我取消了,其他加成再后续版本回归
