### ISSUE TITLE
自爆不会爆炸

### ISSUE THREAD

**Issue by YangChongQuan** [CSGOGAMERS-Community/CG-Server#34]
买自爆 双击F 不自爆 灯都在开关 都不会自爆。
触发原因不知道。有时候可以自爆，有时候不可以 demo录像时间
2017-04-25 15:11:11 dust night

**Comment by Kxnrl** [comment]
双击在0.2s之内看看

**Comment by YangChongQuan** [comment]
可能还需要测试 大概三四天前我就自爆 FF没反应， 下一次当T  买了双击就炸了。我就怎么没在意
我F双击速度绝对在0.2了 我是一直FFFFFFFF 疯狂点 就不炸  当时在人群中买的贼激动 绝对FFF非常快。灯光一直在闪 不知道什么触发条件才不会爆炸。

**Comment by Kxnrl** [comment]
FF控制顺序优先级

遥控炸弹>光学迷彩>自爆
