### ISSUE TITLE
JB服-越狱服与规则吻合的更新

### ISSUE THREAD

**Issue by CGMentos** [CSGOGAMERS-Community/CG-Server#41]
# 狱长重甲争议
狱长不会在3:30时取消,而是在规则禁止继续额外的死亡游戏,**卸载重甲(发100点头盔+护甲替换)**,正在进行的死亡游戏需有序中止.
如果此时狱长已经下令中止游戏而死亡游戏不能手动强制中止而死亡的玩家不算狱长头上.
有当过狱长的玩家的回合,在带领玩家进行过至少1次死亡游戏,在此之后理应允许在3分钟之后知道这应该是混战模式,允许狱长下达攻城命令.
狱长必须在3:00时给予囚犯自由活动

> 意思是3:30之后3:00之前狱长还能额外对囚犯进行系统式管理,但是不能玩死亡游戏

> 考虑到正常的混战也只是2分多钟,鉴于越狱地图普片较小,就算非常大,也是迷你游戏合集,不会复杂到哪里,所以给3分钟自由暴动时间足矣

正式规则条例:
`1.狱长在3:30时需要中止当前的死亡游戏,如果正在进行的地图死亡游戏不能手动强制终止,在死亡游戏内的玩家死亡不算狱长头上.`
`2.狱长在3:30后不能玩死亡游戏`
`3.LR时狱长必须卸载重甲(按Y发送!uw)`
`4.有狱长玩家带领囚犯进行至少1次死亡游戏后,允许狱长在给予囚犯自由活动前后下达攻城命令`

# LR范围提升
1.LR人数由2个提示到5个

> 5个囚犯时不能玩死亡游戏,干脆越狱模式变LR模式

# 越狱服没有平局
00:01时处死所有囚犯.

**Comment by Kxnrl** [comment]
LR不考虑改动.最多改动触发人数.

除死囚犯可以.

重甲的话,可以设定为平衡/时间到直接取消,从而避免下狱长

但是你要考虑好是下狱长还是下重甲.因为只是下重甲,可以重新上狱长卡回来.
