### ISSUE TITLE
ZE一些地图存在的问题

### ISSUE THREAD

**Issue by DohiCircle** [CSGOGAMERS-Community/CG-Server#43]
ze_shroomforest_p6 蘑菇1EX2boss鬼斯形态1s秒上天即死，黑洞也只能续1s 建议:降低或取消这个升力
ze_pkmn_adventure_v7_2 胜利存在问题貌似没写入核爆开关ZMWIN

**Comment by Kxnrl** [comment]
没看懂你说什么

**Comment by DohiCircle** [comment]
就是地图存在BUG能修么不修严重影响游戏体验，不行就CLOSE了

**Comment by Kxnrl** [comment]
你能说明白点不? 你这巴拉巴拉打了一串,我都不知道你说的是什么

**Comment by DohiCircle** [comment]
就是说蘑菇1EX2那一关BOSS的鬼斯形态是把人往上吸到天花板撞死，然后以前吸力用黑洞能解然后打死BOSS，现在不知道怎么回事吸力直接一下子上天，连黑洞的机会都没有，意思说EX2无法过关

**Comment by DohiCircle** [comment]
神奇宝贝那张图你没加核爆已到达导致只有僵尸胜利，就是那个EZWIN判定插件

**Comment by Kxnrl** [comment]
不可能的.核爆不需要判定.除非地图伤害很奇葩.

**Comment by DohiCircle** [comment]
你那个EZWIN插件不是没那个核爆提示就算EZWIN啊

**Comment by DohiCircle** [comment]
还有一堆伤害奇葩的没修呢生化危机:逃离蜂巢，最终撤离:停车场大楼，龙珠

**Comment by Kxnrl** [comment]
`public void CG_OnClientDeath(int client, int attacker, int assister, bool headshot, const char[] weapon)
{
	g_iLeft[client] = RoundToNearest(GetConVarFloat(g_hRespawnDelay));
	CreateTimer(1.0, Timer_Countdown, client, TIMER_REPEAT);

	if(g_bBlockRespawn || !client || attacker || !StrEqual(weapon, "trigger_hurt"))
		return;
	
	if(GetClientTeam(client) == 3)
		return;

	float fGameTime = GetGameTime();

	if(fGameTime - g_fDeathTime[client] - GetConVarFloat(g_hRespawnDelay) < 2.0)
	{
		PrintToChatAll("[\x0CCG\x01]  \x07地图核爆已启动\x01...");
		g_bBlockRespawn = true;
		
		if(g_tCheckingTimer != INVALID_HANDLE)
		{
			ClearTimer(g_tCheckingTimer);
			g_bRequestCheck = false;
			CS_TerminateRound(10.0, g_bBlockRespawn ? CSRoundEnd_CTWin : CSRoundEnd_TerroristWin);
			PrintToChatAll("[\x0CCG\x01]   %s", g_bBlockRespawn ? "\x0C Humans win !" : "\x07 Zombies win !");
		}

		return;
	}

	g_fDeathTime[client] = fGameTime;
}
`

**Comment by DohiCircle** [comment]
然后呢看不懂代码这个要怎么改比如核爆伤害，一些图都没加过“地图核爆已启动”

**Comment by DohiCircle** [comment]
补充ze_kororinpa_v1_6 
这张图开局一堆雷可以捡
重点是有烟雾（聚合!!!!!!）和心跳雷（卡服雷）

**Comment by Kxnrl** [comment]
你给个列表,核爆有问题的都贴出来
