### ISSUE TITLE
关于ZE服的RTV问题

### ISSUE THREAD

**Issue by RealRailgun** [CSGOGAMERS-Community/CG-Server#46]
现在一次RTV结束之后出选图选项，选完后地图时间不是马上为0而是继续，要重新一轮RTV才生效。当地图时间还有几分钟结束出现选图时，选完后又重新加了20分钟

**Comment by Kxnrl** [comment]
没看懂

**Comment by RealRailgun** [comment]
就是RTV选完图了之后，地图时间不是马上变0的，要重新RTV一波才可以

**Comment by Kxnrl** [comment]
RTV选完图之后,要等到当回合结束吧.

**Comment by RealRailgun** [comment]
就是，比如一张图还有30分钟结束，以前RTV后当回合就时间为0了，但是现在RTV之后30分钟，还是30分钟没变0

**Comment by Kxnrl** [comment]
fixed

**Comment by DohiCircle** [comment]
有么我今天在2F跑图然后进去是贴图者，我RTV换图选好，然后！！！！
timeleft=1
timeleft=60
大概那个意思剩余时间还是60
我又手动rtv一次
是只修了1F么？

**Comment by Kxnrl** [comment]
对.二服留着备用

**Comment by Kxnrl** [comment]
fixed
