### ISSUE TITLE
TTT2周年策划

### ISSUE THREAD

**Issue by zhenxiaoxiao** [CSGOGAMERS-Community/CG-Server#52]
2周年活动

一.每日累计在线时间钻石奖励

二.累计3天在线60分钟奖励200信用点，5天300,10天3钻石，15天任意皮肤1天加300信用点。进行循环

三.从活动开始作为叛徒身份击杀平民200个奖励100点，500个300点，1000个500点，1500个5钻石
   侦探身份击杀叛徒100个300点。200个3钻石
   平民身份击杀叛徒100个300点。200个3钻石

四.击杀重甲玩家奖励20信用点有几率获得2钻石

五.每张地图最后一局生存的平民，侦探玩家！将在下张地图第一局获得猫灵赠送的100点护甲

六.2周年当天3点30在线，可在第二天于论坛获得一次抽取奖励的机会，奖励信用点，钻石，（少量）皮肤3天，2周年皮肤7天3个，永久1个

七.top榜正确击杀榜！top1.可获得专属认证，2周年皮肤，top2.3获得2周年皮肤，top4.5.可获得2周年皮肤30天

八.充值榜！具体冲多少送多少和top送多少大佬定

九.萌新初次加入cg社区可获得猫灵赠送的888信用点和3天随机皮肤

十.每日签到可随机获得store道具。

建议：
      2周年出个（元老）认证奖励给那些从头就支持cg的玩家
      希望一个玩家可以获得多个认证（每个模式一个）可自由切换认证！奖励不加

**Comment by DohiCircle** [comment]
SOLOOOOOOO
