### ISSUE TITLE
TTT二周年计划-

### ISSUE THREAD

**Issue by YangChongQuan** [CSGOGAMERS-Community/CG-Server#53]
活动①
当T刀杀大D(秒杀刀除外，击杀当大D的OP奖励翻倍)，有30几率奖励22信用点并且有百分之22几率出现暴击奖励222信用点 或者 刀皮肤随机一款(1-24小时，每天最多触发一次)，一天内当T刀22个大D奖励222信誉点或2个钻石 或 刀皮肤随机一款(1-24小时每天最多触发一次。
拌雷、尸体炸弹、自爆等等都可以同理。

活动②
当T biubiu雷炸死大D（击杀当大D的OP奖励翻倍，几率增加）有30几率奖励22信用点并且有百分之22几率出现暴击奖励222信用点 或者 手雷皮肤或 手雷特效 随机一款(1-7天，每天最多触发一次)，一天内biubiu雷炸22个大D奖励222信誉点或2个钻石 或 手雷皮肤或 手雷特效随机一款(1-7天，每天最多触发一次。

活动③
当大D验明叛徒真身40几率奖励22信用点 or  更小几率出现钻石。平民验明叛徒真身20
几率奖励22信用点or 更小几率出现钻石。
活动④
活动时间内 
大D击杀叛徒达到666个 奖励任意皮肤一款 or 刀皮肤 or 翅膀  30-90天 and 15个钻石。
T正确击杀达到1500个 奖励任意皮肤一款 or 刀皮肤 or 翅膀  30-90天and 15个钻石。

平民正确击杀叛徒达到1000个 奖励任意皮肤一款 or 刀皮肤 or 翅膀  30-90天and 15个钻石。

可重复，错误击杀会扣除一个。
活动⑤
每天（达到签到时间）第一句 祝CG二周年生日快乐！  随机一款store 道具1-3天 小几率出现一个月会员。持续15天可获得CG二周年标签
活动⑥
签到送皮肤1-72小时。
活动⑦
在线时间给钻石，和以前一样。
活动⑧
出泰坦显卡和以前奖励一样
活动⑨
大D保护平民胜利并且自己存活 或者  仅有最后二个平民内存活并胜利。 奖励88信用点 or 随机一款store 道具 1-12小时，小几率出现7-30天。

活动⑩
和CP一起游戏时俩人都存活到结束，有几率奖励双方同一款皮肤or 刀 or 翅膀 1-3天，极小几率出现30天。

**Comment by DohiCircle** [comment]
SOLOOOOOOO
