### ISSUE TITLE
CG二周年越狱活动计划

### ISSUE THREAD

**Issue by CGyoungming** [CSGOGAMERS-Community/CG-Server#55]
1、 签到除获得信用点外随机获得商场现有在售皮肤、饰品、音频(1～24小时)，另有0.1%几率额外获得随机标签、字体颜色一个月。
2、连续在线时间满60分钟额外获得10信用点，120分钟额外获得20信用点，150分钟以上每隔30分钟额外获得20点信用点，达到180分钟额外获得2钻石。
3、获胜一局获得2信用点(为防止恶意刷分，需10人以上才可生效。)
4、狱警正确击杀暴动囚犯获得2信用点(十人以上生效。)
5、囚犯暴动击杀狱警获得5信用点(十人以上生效)
6、囚犯击杀狱长获得10信用点(十人以上生效)
7、lr获胜获得5信用点(十人以上生效)
8、最后一个狱警模式狱警屠杀获胜获得1钻石。(十人以上生效)
9、最后一个狱警模式击杀最后一个狱警者获得1钻石。
10、周年庆当天13:30在线获得一次抽奖机会。

**Comment by DohiCircle** [comment]
SOLOOOOOO
