### ISSUE TITLE
TTT二周年计划

### ISSUE THREAD

**Issue by Yirenwuxin** [CSGOGAMERS-Community/CG-Server#64]
1   活动任务
                  平民和侦探击杀一定数量叛徒给予一定数量信用点奖励（例如每击杀10个叛徒给予100点信用点）。
                  叛徒 击杀一定数量平民给予一定数量信用点奖励（例如每击杀20个平民给予100点信用点）。
2  疯狂杀戮
                  活动结束以排行榜排名（活动开始可以重置排行榜）选出正确击杀最多的前3名玩家给予永久专属道具（如代表CG社区的专属皮肤，霓虹，手雷，盾牌......道具）。
3  周年庆狂欢
                   活动期间每在线2个小时给予100点信用点奖励（二周年所以是2小时）。
4  回馈奖励
                   选出活动期间玩家在线时间最长的10名玩家给予一定时长的VIP回馈奖励。

**Comment by CrysisDeathgun** [comment]
3、4.电脑不关的某些人看着你
2.送道具永久太那啥了 用到活动结束？
