### ISSUE TITLE
JB周年庆计划

### ISSUE THREAD

**Issue by CGsheshuiyu** [CSGOGAMERS-Community/CG-Server#66]
1.周年庆期间，给予玩家击杀奖励，囚犯自由前击杀狱警2credits，自由后（无狱长）击杀狱警5credits（仅对注册论坛并绑定steam玩家生效）
2.任意囚犯在自由前击杀狱长5credits（仅对注册论坛并绑定steam玩家生效）
3.成功存活的囚犯和狱警，结束后5credits（仅对注册论坛并绑定steam玩家生效）
4.对于未注册的玩家，无论击杀或被击杀，都只能获得1credits（比如，未注册A，杀死了狱警或者狱长，都只能获得1credits，任何人杀死未注册玩家，也只能获得1credits）为了激励其他人加入社区
5.CT正确击杀囚犯，无论何时都是2credits，并且为了防止刷分，15人以上才触发，或者大于等于3CT时（仅对注册论坛并绑定steam玩家生效）
6.囚犯获胜，mvp玩家随机获得50-100credits或者任意饰品1-2小时（仅注册玩家且5人以上或者大于等于3CT）
7.CT获胜，任职的狱长获得100-200credits或者任意饰品2-3小时（任职时间大于4分钟，15人以上或者大于等于3CT）
8.周年庆基因突变模式，有几率将在下一局出现（本局结束时会提示下局将进行基因突变模式），本模式为小游戏模式，比如可以设计会攻城，然后CT和T都会出现一个基因突变的人，其实就是得到的强化的人，血量可以按人数来，类似最后一个CT一样（比如T有12个人，CT有4个人，CT的强化人就有100+1200*0.8-300血，T的强化人有400血，当然算法可以再改，这个无所谓）双方以保护强化人为目标互相攻打，团灭的一方或先打死强化人的一方获胜，胜方全体200credits奖励，击杀强化人的单独奖励200-300credits或者饰品1天+

**Comment by CrysisDeathgun** [comment]
我觉得应该补充一下自由应该是强制自由 比如3分30 、CT=T、T≤5
