### ISSUE TITLE
ZE核爆存在问题

### ISSUE THREAD

**Issue by DohiCircle** [CSGOGAMERS-Community/CG-Server#72]
（大部分新图可能都没加【核爆已到达】)
ze_titanic_escape_v2_3_p
ze_Parking_p4
ze_dragonball_snakeway_v1_3
ze_raccoon_facility_v6b_pm2
ze_PKMN_Adventure_v7_2
ze_random_p2(可能有)

**Comment by DohiCircle** [comment]
6.3
ze_Island_Escape_p3

**Comment by Kxnrl** [comment]
有的地图版本号不对

**Comment by Kxnrl** [comment]
fixed
