### ISSUE TITLE
关于开箱被吞的皮肤算BUG吗，

### ISSUE THREAD

**Issue by YangChongQuan** [CSGOGAMERS-Community/CG-Server#78]
开四个永久，快速卖了一个存三个全没有，都被吞了，而且被吞的不止我一个，很多人都是。算BUG吗，会返回皮肤吗。

**Comment by YangChongQuan** [comment]
天台榜也查不到我存的永久皮肤的记录。。只有我卖的俩个永久皮肤。。可能是开出来四个卖掉了俩个。。记不清了 当时开的太开心了 没注意  最后清算才发现存的皮肤全被吞了。 平时攒点钱不容易，好不容易欧一把请老大做主。。
![x9r7x n 6dseogf s 4vb](https://cloud.githubusercontent.com/assets/25027405/26272414/105a9490-3d4a-11e7-83a2-2d2f184561fc.png)
![74tthw r9z5b8 ponxol pe](https://cloud.githubusercontent.com/assets/25027405/26272415/10620dce-3d4a-11e7-8c83-28db2fa2df91.png)

**Comment by Kxnrl** [comment]
不算BUG.你点了退出,或者什么都不操作
就当作你放弃领奖

5月20日早上的更新已经解决这个问题

**Comment by YangChongQuan** [comment]
可是 我操作了啊。 我操作的存入 库存。 然后界面才消失 我操作了。

**Comment by YangChongQuan** [comment]
两三次都是这样，然后我存了个十几天的 就进去了，不懂。永久就存不进去。 一个可能出错 两三个都错了吗。。

**Comment by Kxnrl** [comment]
左下角如何提示,具体时间

**Comment by YangChongQuan** [comment]
对不起，当时太激动一个劲开没注意左下角我没想到会出错。我翻demo也看不到开箱消息，我当时开出永久专门发到聊天里想刺激他们一起开。。聊天记录如果有存入数据库可以知道具体时间，demo 是  1f_20170519_20-16-56_ttt_cgtowndev_bud2  9点左右

**Comment by YangChongQuan** [comment]
2017年5月19日    21:01     96129140 1f_20170519_20-16-56_ttt_cgtowndev_bud2.dem.7z

**Comment by Kxnrl** [comment]
DEMO不会显示针对某人的提示.只有全局提示
提示你获得之后.你需要操作选择才会有获得.如果没操作.在5月20日更新之后是卖掉的

**Comment by YangChongQuan** [comment]
好吧。。算了，估计难查到了。我确实操作了，你说没操作会吞我才来发这个询问下，这种情况是否BUG。
