### ISSUE TITLE
ZE 吸血天赋问题

### ISSUE THREAD

**Issue by DohiCircle** [CSGOGAMERS-Community/CG-Server#79]
神图可以让血量高于100上限 但是有吸血就会回到100 
上次5-15更新之前貌似有段时间不会回到100
虽然肾上腺素可以获得300血上限但是还是很麻烦毕竟得先花10000
如果不会降血就可以买个重甲防抓
反正就提一下（主要是傻子老滚17000+一开枪就剩100了）

**Comment by Kxnrl** [comment]
????

**Comment by DohiCircle** [comment]
就是吸血天赋会把神器加的额外血量清掉
拿MAKO来说3级奶225血 我带吸血8级爆头僵尸 血就只有100了

**Comment by Kxnrl** [comment]
fix
