### ISSUE TITLE
ZE 组内BUG反馈

### ISSUE THREAD

**Issue by DohiCircle** [CSGOGAMERS-Community/CG-Server#80]
1.最近开始有些图下不了很多人 可能网盘出问题了
2.神器等级 比如上古 米纳斯之类的 都是用mvp星数表示 假分几率高
3.好像说有假神器 我不清楚
4.一个人就能rtv换图 以前有过不记得什么图姑且挂着

**Comment by DohiCircle** [comment]
今天31重甲不防抓!!!!

**Comment by Kxnrl** [comment]
31本来就不防抓,起码要34 35
