### ISSUE TITLE
TTT  ZE  BUG

### ISSUE THREAD

**Issue by zhenxiaoxiao** [CSGOGAMERS-Community/CG-Server#89]
TTT
1.光学迷彩解除之后枪械丢失
2.a1 a4 天赋不给回复子弹
3.爆炸狙点数错误 （标价2000/2实际3000/3）
ZE
1.变母体瞬间挥刀会在传送之前感染人类
2.变僵尸瞬间有几率会直接被击杀（不会出现100血）
3.车王子弹错误
4，建议加回地图伤害

**Comment by Kxnrl** [comment]
ZE第四点是什么意思.不知道

**Comment by Kxnrl** [comment]
fixed
