### ISSUE TITLE
ZE BUG

### ISSUE THREAD

**Issue by zhenxiaoxiao** [CSGOGAMERS-Community/CG-Server#90]
1.有些地图核爆后，会处死多次，现在的尸变机制是会有微小的时间是人类！然后就导致第二次处死的是人类阵营就会  ez win  ！不加积分
2.老滚地图大卫无法挥刀和释技能

**Comment by Kxnrl** [comment]
没看懂第一点

**Comment by zhenxiaoxiao** [comment]
变僵尸时有一段极短的时间是人类，核爆处死会在那一瞬间处死！结果就是没有僵尸阵营，导致显示ez win！能过关但是通关的人不给分

**Comment by Kxnrl** [comment]
fixed
