### ISSUE TITLE
ZE BUG 以及TTT建议

### ISSUE THREAD

**Issue by zhenxiaoxiao** [CSGOGAMERS-Community/CG-Server#92]
ze  bug
vip投票换图无法生效只能起到选择下张地图的作用，也就是说选图完毕，地图时间不会减少

TTT建议
可以选择一些地图不加长枪，只加手枪或者狙击枪！该地图时叛徒道具100发A1可改为100发tec9或者50发gaygun！这样玩法就变得多样性！可玩性更高

天赋系统加入新天赋 快手：加快切枪速度和换弹速度
增加实名认证或者会员天赋页+1特权

TTTbug
A1,A4,AWP这3把枪有很大几率不加子弹！！！

**Comment by DohiCircle** [comment]
VIP投票相对于过去没做改变吧？

**Comment by Kxnrl** [comment]
子弹已经解决

**Comment by Kxnrl** [comment]
fixed
