### ISSUE TITLE
ZE BUG 以及 TTT BUG

### ISSUE THREAD

**Issue by zhenxiaoxiao** [CSGOGAMERS-Community/CG-Server#98]
ZE
1.人类a在尸变之前扔的道具会在人类a尸变之后对其他人类造成伤害

TTT
1.开局有几率会发放c4,炸弹，可以安放，大d可进行拆除！但回合不会结束

**Comment by Kxnrl** [comment]
你自己吃屎吧.上次我就问过有没有问题.你说没问题

2.这个还不知道什么清空

**Comment by zhenxiaoxiao** [comment]
我也很绝望啊！上次是没问题的，昨天又出现了

**Comment by Kxnrl** [comment]
fixed
